apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micrshopping-ingress-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cors-allow-headers: >-
      DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
  - host: micrshoppingapi.zhanghaiming.site
    http:
      paths:
      - path: /order(/|$)(.*)
        backend:
          serviceName: {{ .Values.orderapi.service.name }}
          servicePort: 80
      - path: /pay(/|$)(.*)
        backend:
          serviceName: {{ .Values.payapi.service.name }}
          servicePort: 80

      - path: /product(/|$)(.*)
        backend:
          serviceName: {{ .Values.productapi.service.name }}
          servicePort: 80

      - path: /account(/|$)(.*)
        backend:
          serviceName: {{ .Values.usermanageapi.service.name }}
          servicePort: 80

  tls:
  - hosts:
    - micrshoppingapi.zhanghaiming.site
    secretName: micrshoppingapi-zhanghaiming-site