stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: src/MicrShopping.OrderApi/Dockerfile
      buildContext: .
      tag: micrshopping/MicrShopping.OrderApi:${CICD_LOCAL_REGISTRY}
      pushRemote: true
      registry: https://rancher.zhanghaiming.site:30003/
timeout: 100
notification: {}
