stages:
- name: publish
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      shellScript: |+
        cd src
        dotnet publish "MicrShopping.Identity/MicrShopping.Identity.csproj" -c Release -o /app/identity/publish

        cd /app/identity/publish
        ls


- name: docker-build
  steps:
  - publishImageConfig:
      dockerfilePath: /app/identity/publish/Dockerfile
      buildContext: .
      tag: micrshopping/micrshopping.identity:${CICD_EXECUTION_ID}
      pushRemote: true
      registry: https://rancher.zhanghaiming.site:30003/
timeout: 100
notification: {}
