stages:
- name: publish
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      shellScript: |+
        cd src
        dotnet publish "MicrShopping.Identity/MicrShopping.Identity.csproj" -c Release -o /app/publish


timeout: 100
notification: {}
