stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: src/MicrShopping.OrderApi/Dockerfile
      buildContext: .
      tag: MicrShopping.OrderApi
      pushRemote: true
      registry: https://192.168.232.131:30003/
timeout: 60
notification: {}
