stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: src/MicrShopping.OrderApi/Dockerfile
      buildContext: .
      tag: MicrShopping.OrderApi
      pushRemote: true
      registry: http://192.168.232.131:6001/
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
      shellScript: docker-compose build
timeout: 60
notification: {}
