stages:
- name: build
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
      shellScript: |-
        pwd
        cd src
        docker build -f MicrShopping.OrderApi/Dockerfile -t micrshopping.orderapi . --no-cache
timeout: 100
notification: {}
