apiVersion: v1
kind: Service
metadata:
  name: {{ include "micrshopping.fullname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
spec:
  type: {{ .Values.identity.service.type }}
  ports:
    - port: {{ .Values.identity.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.identity.service.httpsPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "micrshopping.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
