apiVersion: v1
kind: Service
metadata:
  name: micrshoppingidentityapi-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80tcp01
    nodePort: {{ .Values.identity.serverNodePort.ports.http.nodePort }}
    port: {{ .Values.identity.serverNodePort.ports.http.port }}
    protocol: TCP
    targetPort: 80
  - name: 443tcp01
    nodePort: {{ .Values.identity.serverNodePort.ports.https.nodePort }}
    port: {{ .Values.identity.serverNodePort.ports.https.port }}
    protocol: TCP
    targetPort: 443
  type: NodePort
status:
  loadBalancer: {}
