apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-jrcqx
  creationTimestamp: "2020-03-21T04:38:40Z"
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-postgresql
  name: postgresql
  namespace: default
  resourceVersion: "20572"
  selfLink: /apis/apps/v1/namespaces/default/deployments/postgresql
  uid: 8f16cca1-baa8-41cf-bd6e-17d47db6778c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-postgresql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-03-21T04:39:46Z"
        field.cattle.io/ports: '[[{"containerPort":5432,"dnsName":"postgresql","hostPort":0,"kind":"ClusterIP","name":"5432tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: Admin123456!
        - name: POSTGRES_USER
          value: postgres
        image: postgres:latest
        imagePullPolicy: Always
        name: postgresql
        ports:
        - containerPort: 5432
          name: 5432tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-21T04:38:59Z"
    lastUpdateTime: "2020-03-21T04:38:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-21T04:38:40Z"
    lastUpdateTime: "2020-03-21T04:39:55Z"
    message: ReplicaSet "postgresql-6df987b48c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
