name: harbor
version: 1.2.0
appVersion: 1.9.0
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
home: https://goharbor.io
icon: file://../harbor_logo.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
maintainers:
- name: jessehu
  email: huh@vmware.com
- name: paulczar
  email: username.taken@gmail.com
engine: gotpl
