apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webmvc.service.name }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
spec:
  type: {{ .Values.webmvc.service.type }}
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: {{ .Values.webmvc.service.httpPort }}
  - name: "https"
    port: 443
    protocol: TCP
    targetPort: {{ .Values.webmvc.service.httpsPort }}      
  selector:
    component: {{ .Values.webmvc.deployment_name }}
