apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-jrcqx
    field.cattle.io/publicEndpoints: '[{"addresses":["172.31.136.0"],"port":32302,"protocol":"TCP","serviceName":"default:micrshoppingidentityapi-nodeport","allNodes":true},{"addresses":["172.31.136.0"],"port":30402,"protocol":"TCP","serviceName":"default:micrshoppingidentityapi-nodeport","allNodes":true}]'
  creationTimestamp: "2020-03-21T05:08:33Z"
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-micrshoppingidentityapi
  name: micrshoppingidentityapi
  namespace: default
  resourceVersion: "24642"
  selfLink: /apis/apps/v1/namespaces/default/deployments/micrshoppingidentityapi
  uid: 5d351d08-9c89-4610-b7a5-58a25155f646
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-micrshoppingidentityapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-03-21T05:08:25Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"micrshoppingidentityapi-nodeport","hostPort":0,"kind":"NodePort","name":"80tcp01","protocol":"TCP","sourcePort":0},{"containerPort":443,"dnsName":"micrshoppingidentityapi-nodeport","hostPort":0,"kind":"NodePort","name":"443tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-micrshoppingidentityapi
    spec:
      containers:
      - image: micrshopping.identityapi
        imagePullPolicy: Never
        name: micrshoppingidentityapi
        ports:
        - containerPort: 80
          name: 80tcp01
          protocol: TCP
        - containerPort: 443
          name: 443tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-21T05:08:35Z"
    lastUpdateTime: "2020-03-21T05:08:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-21T05:08:33Z"
    lastUpdateTime: "2020-03-21T05:08:35Z"
    message: ReplicaSet "micrshoppingidentityapi-cd5774bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
