apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.fullname" . }}
  labels:
  {{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ .Files.Get "cert/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "cert/tls.key" | b64enc }}

  POSTGRES_USER: {{ .Values.pgsql.env.username }}
  POSTGRES_PASSWORD: {{ .Values.pgsql.env.password }}

  RABBITMQ_USER: {{ .Values.rabbitmq.env.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.env.password }}
