apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.secretname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ .Values.secret | default (randAlphaNum 16) | b64enc | quote }}

  ConnectionStrings__UserID: {{ .Values.pgsql.env.username | b64enc | quote }}
  ConnectionStrings__Password: {{ .Values.pgsql.env.password | b64enc | quote }}
  ConnectionStrings__Host: {{ .Values.pgsql.service.name | b64enc | quote }} 	

  RabbitMQ__Host:	{{ .Values.rabbitmq.service.name | b64enc | quote }}
  RabbitMQ__UserName: {{ .Values.rabbitmq.env.username | b64enc | quote }}
  RabbitMQ__Password: {{ .Values.rabbitmq.env.password | b64enc | quote }}
