apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.fullname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.pgsql.env.username }}
  POSTGRES_PASSWORD: {{ .Values.pgsql.env.password }}

  RABBITMQ_USER: {{ .Values.rabbitmq.env.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.env.password }}
