apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.fullname" . }}
  labels:
  {{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.pgsql.env.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.pgsql.env.password | b64enc | quote }}

  rabbitmq_USER: {{ .Values.rabbitmq.env.username | b64enc | quote }}
  rabbitmq_PASSWORD: {{ .Values.rabbitmq.env.password | b64enc | quote }}
