apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.secretname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ .Values.secret | default (randAlphaNum 16) | b64enc | quote }}

  ConnectionStrings_UserID: {{ .Values.pgsql.env.username }}
  ConnectionStrings_Password: {{ .Values.pgsql.env.password }}
  ConnectionStrings_Host: {{ .Values.pgsql.service.name }} 	

  RabbitMQ_Host:	{{ .Values.rabbitmq.service.name }}
  RabbitMQ_UserName: {{ .Values.rabbitmq.env.username }}
  RabbitMQ_Password: {{ .Values.rabbitmq.env.password }}
