apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micrshopping-ingress-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: micrshoppingapi.zhanghaiming.site
    http:
      paths:
      - path: /order(/|$)(.*)
        backend:
          serviceName: {{ .Values.orderapi.service.name }}
          servicePort: 80
      - path: /pay(/|$)(.*)
        backend:
          serviceName: {{ .Values.payapi.service.name }}
          servicePort: 80

      - path: /product(/|$)(.*)
        backend:
          serviceName: {{ .Values.productapi.service.name }}
          servicePort: 80

      - path: /account(/|$)(.*)
        backend:
          serviceName: {{ .Values.usermanageapi.service.name }}
          servicePort: 80

  tls:
  - hosts:
    - micrshoppingapi.zhanghaiming.site
    secretName: micrshoppingapi-zhanghaiming-site