apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgsql.deployment_name }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
    component: {{ .Values.pgsql.deployment_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "micrshopping.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "micrshopping.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: {{ .Values.pgsql.deployment_name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.pgsql.image.repository }}:{{ .Values.pgsql.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.pgsql.env.password }}
        - name: POSTGRES_USER
          value: {{ .Values.pgsql.env.username }}
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
