apiVersion: v1
kind: Secret
metadata:
  name: {{ template "micrshopping.secretname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ .Values.secret | default (randAlphaNum 16) | b64enc | quote }}

  POSTGRES_PASSWORD: {{ .Values.pgsql.env.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.pgsql.env.username | b64enc | quote }}

  RabbitMQ__UserName: {{ .Values.rabbitmq.env.username | b64enc | quote }}
  RabbitMQ__Password: {{ .Values.rabbitmq.env.password | b64enc | quote }}

  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin4.env.username | b64enc | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin4.env.password | b64enc | quote }}