apiVersion: v1
kind: Service
metadata:
  name: {{ include "micrshopping.fullname" . }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
  {{range $element := .Values.rabbitmq.service.oort }}
    - port: {{ $element }}
      targetPort: http
      protocol: TCP
      name: http
  {{ end }}
    
  selector:
    app.kubernetes.io/name: {{ include "micrshopping.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
