version: '3.4'

services:

  micrshopping.orderapi:
    image: ${DOCKER_REGISTRY-}micrshoppingorderapi
    build:
      context: .
      dockerfile: MicrShopping.OrderApi/Dockerfile

  micrshopping.payapi:
    image: ${DOCKER_REGISTRY-}micrshoppingpayapi
    build:
      context: .
      dockerfile: MicrShopping.PayApi/Dockerfile


  micrshopping.identity:
    image: ${DOCKER_REGISTRY-}micrshoppingidentity
    build:
      context: .
      dockerfile: MicrShopping.Identity/Dockerfile

  micrshopping.apigateway:
    image: ${DOCKER_REGISTRY-}micrshoppingapigateway
    build:
      context: .
      dockerfile: MicrShopping.ApiGateway/Dockerfile

