version: '3.4'

services:
  sqldata:
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Admin123456!
      - ACCEPT_EULA=Y
    ports:
      - "14336:1433"
    volumes:
      - D://docker/sqlserver:/var/opt/mssql

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123456
    ports:
      - "15675:15672"
      - "5675:5672"
      - "5676:5671"

  consul:
    container_name: consul
    volumes:
      - D://docker/consul/data:/consul/data
      - D://docker/consul/config:/consul/config
    ports:
      - "8500:8500"
    

  micrshopping.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OrderConnectionStrings=${orderapi:-Server=sqldata;Database=OrderDB;User Id=sa;Password=Admin123456!}
      - RabbitMQHost=${RabbitMQHost:-rabbitmq}
      - RabbitMQUserName=admin
      - RabbitMQPassword=admin123456
      
      - scheme=https
      - ip=192.168.0.189
      - port=25668
      - ConsulAddress=http://192.168.0.189:8500
      - ServerName=Shopping

    ports:
      - "25667:80"
      - "25668:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.payapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PayConnectionStrings=${payapi:-Server=sqldata;Database=PayDB;User Id=sa;Password=Admin123456!}
      - RabbitMQHost=${RabbitMQHost:-rabbitmq}
      - RabbitMQUserName=admin
      - RabbitMQPassword=admin123456
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro



  micrshopping.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "25660:80"
      - "25661:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
