version: '3.4'

services:

  micrshopping.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- OrderConnectionStrings=${orderstr:-Host=postgres;Port=5432;Database=OrderDB;User ID=postgres;Password=Admin123456!;Pooling=true;}

      - ConnectionStrings__Host=postgres
      - ConnectionStrings__Port=5432
      - ConnectionStrings__Database=OrderDB
      - ConnectionStrings__UserID=postgres
      - ConnectionStrings__Password=Admin123456!
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123456
      - RabbitMQ__Port=5672

#      - RabbitMQ__Host=rabbitmq  对象形式的参数写法 等同 RabbitMQ:{Host:"rabbitmq"}
#      - RabbitMQ__0__UserName=admin  数组形式的参数写法 等同 RabbitMQ:[{UserName:"admin"}]

      - scheme=http
      - ip=micrshopping.orderapi
      - port=80
      - ConsulAddress=http://consul4:8500
      - ServerName=orderapi

      - IdentityUrl=http://192.168.0.189:5008
    ports:
      - 5004:80
      - 5003:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.payapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- PayConnectionStrings=${paystr:-Host=postgres;Port=5432;Database=PayDB;User ID=postgres;Password=Admin123456!;Pooling=true;}

      - ConnectionStrings__Host=postgres
      - ConnectionStrings__Port=5432
      - ConnectionStrings__Database=PayDB
      - ConnectionStrings__UserID=postgres
      - ConnectionStrings__Password=Admin123456!
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123456
      - RabbitMQ__Port=5672

      - scheme=http
      - ip=micrshopping.payapi
      - port=80
      - ConsulAddress=http://consul4:8500
      - ServerName=payapi

      - IdentityUrl=http://192.168.0.189:5008
    ports:
      - 5006:80
      - 5005:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  micrshopping.usermanageapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

      #- IdentityConnectionStrings=${usermanagestr:-Host=postgres;Port=5432;Database=IdentityDB;User ID=postgres;Password=Admin123456!;Pooling=true;}

      - ConnectionStrings__Host=postgres
      - ConnectionStrings__Port=5432
      - ConnectionStrings__Database=IdentityDB
      - ConnectionStrings__UserID=postgres
      - ConnectionStrings__Password=Admin123456!
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123456
      - RabbitMQ__Port=5672
      
      - scheme=http
      - ip=micrshopping.usermanageapi
      - port=80
      - ConsulAddress=http://consul4:8500
      - ServerName=usermanageapi

      - IdentityUrl=http://192.168.0.189:5008
    ports:
      - 5016:80
      - 5017:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # 生产环境 Product nginx使用http ,但是在IIS中部署必须使用https
      - ASPNETCORE_URLS=https://+:443;http://+:80  
      #- IdentityConnectionStrings=${identitystr:-Host=postgres;Port=5432;Database=IdentityDB;User ID=postgres;Password=Admin123456!;Pooling=true;}

      - ConnectionStrings__Host=postgres
      - ConnectionStrings__Port=5432
      - ConnectionStrings__Database=IdentityDB
      - ConnectionStrings__UserID=postgres
      - ConnectionStrings__Password=Admin123456!

      - scheme=http
      - ip=micrshopping.identity
      - port=80
      - ConsulAddress=http://consul4:8500
      - ServerName=identityapi

      - IdentityUrl=http://192.168.0.189:5008

      - Clients__MVCUrl=http://192.168.0.189:5012
      - Clients__JsVueUrl=http://192.168.0.189:5015
    ports:
      - 5008:80
      - 5007:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

      - scheme=https
      - ip=192.168.0.189
      - port=5001

    ports:
      - 5002:80
      - 5001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  micrshopping.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ProductConnectionStrings=${productstr:-Host=postgres;Port=5432;Database=ProductDB;User ID=postgres;Password=Admin123456!;Pooling=true;}

      
      - ConnectionStrings__Host=postgres
      - ConnectionStrings__Port=5432
      - ConnectionStrings__Database=ProductDB
      - ConnectionStrings__UserID=postgres
      - ConnectionStrings__Password=Admin123456!
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123456
      - RabbitMQ__Port=5672

      - scheme=http
      - ip=micrshopping.productapi
      - port=80
      - ConsulAddress=http://consul4:8500
      - ServerName=productapi

      - IdentityUrl=http://192.168.0.189:5008
    ports:
      - 5010:80
      - 5009:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro







  micrshopping.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

      - IdentityUrl=http://192.168.0.189:5008
      - OrderServerUrl=http://192.168.0.189:5004
    ports:
      - 5012:80
      - 5011:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
