apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin4.service.name }}
  labels:
{{ include "micrshopping.labels" . | indent 4 }}
spec:
  type: {{ .Values.pgadmin4.service.type }}
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: {{ .Values.pgadmin4.service.port }}     
  selector:
    component: {{ .Values.pgadmin4.deployment_name }}
